name : Postman collection workflow
on:
 push:
   branches: [main]
 workflow_dispatch:  
 schedule: 
     - cron: "30 02 * * *" # 8 am IST Every Day
     - cron: "00 14 * * * " # 730 pm IST Every Day
     - cron: "00 06 * * 1-5" # 1130 am IST Monday - Friday
jobs:
 run-postman-tests:
  runs-on: ubuntu-latest

  steps:
    - name: Check out the code
      uses: actions/checkout@v5.0.0

    - name: Install node js and NPM
      uses: actions/setup-node@v5.0.0
      with:
       node-version : '22'
    - name: Install Newman & extra html reorter
      run: | #| used for multiline
            npm install -g newman
            npm install -g newman-reporter-htmlextra

    - name: Run the Postman collection with newman
      run: |
       newman run 'InWarranty-flow Collection No csv.postman_collection.json' \
       -e QA.postman_environment.json \
       -d 'test data.csv' \
       -r cli,htmlextra \
       --reporter-htmlextra-export ./newman/index.html
       
    - name: Newman Report
      if: always()  #Ensure workflow stepexecutes if test fails too
      uses: actions/upload-artifact@v4.6.2
      with:
       name: Newman report
       path: newman/*.html

    - name: Creating github page branch
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: newman/
        
       
     
      
    
